### ISSUE TITLE
install error on RaspberryMatic

### ISSUE THREAD

**Issue by NestWolfsteiner** [hobbyquaker/check_homematic#4]
installing as root with "npm install -g check_homematic" terminates with error "Unhandled rejection Error: EROFS: read-only file system"

**Comment by hobbyquaker** [comment]
this is a nagios/icinga plugin. it is not meant to be installed on a ccu/rasperrymatic. you have to install it on the host that runs nagios/icinga

**Comment by NestWolfsteiner** [comment]
many thanks for your explanation
